# Generated by Django 4.0.2 on 2022-02-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_food_photo_foodrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='foodrate',
            old_name='food_id',
            new_name='food',
        ),
    ]
