# Generated by Django 4.0.2 on 2022-03-02 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('food', '0007_alter_food_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='post.post'),
        ),
    ]
